sudo: required
dist: xenial
language: python
virtualenv:
  system_site_packages: true
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- pytest
- coverage run test/test_operations.py
after_success: coveralls
after_script: cd ~
deploy:
  
